
link_dict={
	"../manual.html":"http://aleksversus.narod.ru/index/easy_math_3/0-73",
	"vspomogatelnye_funkcii/0-74.html":"http://aleksversus.narod.ru/index/vspomogatelnye_funkcii/0-74",
	"operacii_s_drobnymi_chislami/0-75.html":"http://aleksversus.narod.ru/index/operacii_s_drobnymi_chislami/0-75",
	"logicheskie_operacii/0-76.html":"http://aleksversus.narod.ru/index/logicheskie_operacii/0-76",
	"operacii_s_tekstom/0-77.html":"http://aleksversus.narod.ru/index/operacii_s_tekstom/0-77",
	"operacii_s_shestnadcaterichnymi_chislami/0-78.html":"http://aleksversus.narod.ru/index/operacii_s_shestnadcaterichnymi_chislami/0-78",
	"operacii_s_massivami/0-79.html#em_arr_insert":"http://aleksversus.narod.ru/index/operacii_s_massivami/0-79#em_arr_insert",
	"operacii_s_massivami/0-79.html#em_arr_chtype":"http://aleksversus.narod.ru/index/operacii_s_massivami/0-79#em_arr_chtype",
	"operacii_s_massivami/0-79.html#em_arr_print":"http://aleksversus.narod.ru/index/operacii_s_massivami/0-79#em_arr_print",
	"operacii_s_massivami/0-79.html#em_fewarrs_print":"http://aleksversus.narod.ru/index/operacii_s_massivami/0-79#em_fewarrs_print",
	"operacii_s_massivami/0-79.html#em_arr_clear":"http://aleksversus.narod.ru/index/operacii_s_massivami/0-79#em_arr_clear",
	"operacii_s_massivami_stranica_2/0-80.html#em_arr_randFill":"http://aleksversus.narod.ru/index/operacii_s_massivami_stranica_2/0-80#em_arr_randFill",
	"operacii_s_massivami_stranica_2/0-80.html#em_arr_strtFill":"http://aleksversus.narod.ru/index/operacii_s_massivami_stranica_2/0-80#em_arr_strtFill",
	"operacii_s_massivami_stranica_2/0-80.html#em_arr_sort":"http://aleksversus.narod.ru/index/operacii_s_massivami_stranica_2/0-80#em_arr_sort",
	"operacii_s_massivami_stranica_2/0-80.html#em_arr_restand":"http://aleksversus.narod.ru/index/operacii_s_massivami_stranica_2/0-80#em_arr_restand",
	"operacii_s_massivami_stranica_2/0-80.html#em_arr_desort":"http://aleksversus.narod.ru/index/operacii_s_massivami_stranica_2/0-80#em_arr_desort",
	"operacii_s_massivami_stranica_2/0-80.html#em_arr_simpl":"http://aleksversus.narod.ru/index/operacii_s_massivami_stranica_2/0-80#em_arr_simpl",
	"operacii_s_massivami_stranica_2/0-80.html#em_arr_find":"http://aleksversus.narod.ru/index/operacii_s_massivami_stranica_2/0-80#em_arr_find",
	"operacii_s_celymi_chislami/0-81.html":"http://aleksversus.narod.ru/index/operacii_s_celymi_chislami/0-81",
	"rabota_s_koordinatnoj_setkoj/0-82.html":"http://aleksversus.narod.ru/index/rabota_s_koordinatnoj_setkoj/0-82",
	"istorija_versij/0-83.html":"http://aleksversus.narod.ru/index/istorija_versij/0-83"
}
